project: 
  type: website
  output-dir: docs 

site-url: "https://blade-sp.github.io/personal-website/"

website:
  title: "Riccardo Spada"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Resources
        href: resources.qmd
      - text: CV
        href: cv.qmd
  page-footer:
    left: "Â© 2025 Riccardo Spada"
    right: "Made with [Quarto](https://quarto.org)"
    # Add a logo or image to the navbar:
    # logo: logo.png   
    # Add a custom favicon:
    # favicon: favicon.ico   

format:
  html:
    theme: flatly   
    css: 
      - palette/warm-jay.css
      - styles.css
    smooth-scroll: true
    highlight-style: github
    toc: false