project: 
  type: website
  output-dir: docs 

site-url: "https://blade-sp.github.io/personal-website/"

website:
  title: "Riccardo Spada"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Resources
        href: resources.qmd
      - text: CV
        href: cv.qmd
  page-footer:
    center: "Â© Riccardo Spada 2025"

  favicon: assets/favicon/favicon.ico   

format:
  html:
    theme: flatly   
    css: 
      - styles.css
    smooth-scroll: true
    highlight-style: github
    toc: false